title: Asma Neji - Junior Cybersecurity Engineer
description: Specializing in telecommunications, networks, cybersecurity, and AI. Insights on threat intelligence, secure infrastructures, and AI-driven security.
author: Asma Neji
email: asmaneji20@gmail.com
baseurl: ""
url: "https://asma812.github.io"

theme: minima  # Simple built-in theme; change to 'hacker' or others if desired

# Blog settings
show_excerpts: true

# Navigation
header_pages:
  - index.md
  - blog.md
  - about.md
  - contact.md
  - telecom.md

# Social links
social_links:
  linkedin: asma-neji
  github: Asma812
  phone: +216 97 322 007
